//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using System.Globalization;
using System.IO;
using Keg247.Qif.Transactions;
using Keg247.Qif.Transactions.Fields;

namespace Keg247.Qif.Writers
{
    using System.Threading.Tasks;
    static partial class MemorizedTransactionListWriter
    {
        internal static async Task WriteAsync(TextWriter writer, ICollection<MemorizedTransactionListTransaction> list)
        {
            if ((list != null) && (list.Count > 0))
            {
                await (writer.WriteLineAsync(Headers.MemorizedTransactionList)).ConfigureAwait(true);

                foreach (MemorizedTransactionListTransaction item in list)
                {
                    foreach (string address in item.Address)
                    {
                        await (writer.WriteAsync(MemorizedTransactionListFields.Address)).ConfigureAwait(true);
                        await (writer.WriteLineAsync(address)).ConfigureAwait(true);
                    }

                    await (writer.WriteAsync(MemorizedTransactionListFields.AmortizationCurrentLoanBalance)).ConfigureAwait(true);
                    await (writer.WriteLineAsync(item.AmortizationCurrentLoanBalance.ToString(CultureInfo.CurrentCulture))).ConfigureAwait(true);

                    await (writer.WriteAsync(MemorizedTransactionListFields.AmortizationFirstPaymentDate)).ConfigureAwait(true);
                    await (writer.WriteLineAsync(item.AmortizationFirstPaymentDate.ToString("d"))).ConfigureAwait(true);

                    await (writer.WriteAsync(MemorizedTransactionListFields.AmortizationInterestRate)).ConfigureAwait(true);
                    await (writer.WriteLineAsync(item.AmortizationInterestRate.ToString(CultureInfo.CurrentCulture))).ConfigureAwait(true);

                    await (writer.WriteAsync(MemorizedTransactionListFields.AmortizationNumberOfPaymentsAlreadyMade)).ConfigureAwait(true);
                    await (writer.WriteLineAsync(item.AmortizationNumberOfPaymentsAlreadyMade.ToString(CultureInfo.CurrentCulture))).ConfigureAwait(true);

                    await (writer.WriteAsync(MemorizedTransactionListFields.AmortizationNumberOfPeriodsPerYear)).ConfigureAwait(true);
                    await (writer.WriteLineAsync(item.AmortizationNumberOfPeriodsPerYear.ToString(CultureInfo.CurrentCulture))).ConfigureAwait(true);

                    await (writer.WriteAsync(MemorizedTransactionListFields.AmortizationOriginalLoanAmount)).ConfigureAwait(true);
                    await (writer.WriteLineAsync(item.AmortizationOriginalLoanAmount.ToString(CultureInfo.CurrentCulture))).ConfigureAwait(true);

                    await (writer.WriteAsync(MemorizedTransactionListFields.AmortizationTotalYearsForLoan)).ConfigureAwait(true);
                    await (writer.WriteLineAsync(item.AmortizationTotalYearsForLoan.ToString(CultureInfo.CurrentCulture))).ConfigureAwait(true);

                    await (writer.WriteAsync(MemorizedTransactionListFields.Amount)).ConfigureAwait(true);
                    await (writer.WriteLineAsync(item.Amount.ToString(CultureInfo.CurrentCulture))).ConfigureAwait(true);

                    if (!string.IsNullOrEmpty(item.Category))
                    {
                        await (writer.WriteAsync(MemorizedTransactionListFields.Category)).ConfigureAwait(true);
                        await (writer.WriteLineAsync(item.Category)).ConfigureAwait(true);
                    }

                    if (!string.IsNullOrEmpty(item.ClearedStatus))
                    {
                        await (writer.WriteAsync(MemorizedTransactionListFields.ClearedStatus)).ConfigureAwait(true);
                        await (writer.WriteLineAsync(item.ClearedStatus)).ConfigureAwait(true);
                    }

                    if (!string.IsNullOrEmpty(item.Memo))
                    {
                        await (writer.WriteAsync(MemorizedTransactionListFields.Memo)).ConfigureAwait(true);
                        await (writer.WriteLineAsync(item.Memo)).ConfigureAwait(true);
                    }

                    if (!string.IsNullOrEmpty(item.Payee))
                    {
                        await (writer.WriteAsync(MemorizedTransactionListFields.Payee)).ConfigureAwait(true);
                        await (writer.WriteLineAsync(item.Payee)).ConfigureAwait(true);
                    }

                    foreach (int i in item.SplitCategories.Keys)
                    {
                        await (writer.WriteAsync(MemorizedTransactionListFields.SplitCategory)).ConfigureAwait(true);
                        await (writer.WriteLineAsync(item.SplitCategories[i])).ConfigureAwait(true);
                        await (writer.WriteAsync(MemorizedTransactionListFields.SplitAmount)).ConfigureAwait(true);
                        writer.WriteLine(item.SplitAmounts[i]);

                        string value;
                        if (item.SplitMemos.TryGetValue(i, out value))
                        {
                            await (writer.WriteAsync(MemorizedTransactionListFields.SplitMemo)).ConfigureAwait(true);
                            await (writer.WriteLineAsync(value)).ConfigureAwait(true);
                        }
                    }

                    await (writer.WriteAsync(MemorizedTransactionListFields.Transaction)).ConfigureAwait(true);
                    switch (item.Type)
                    {
                        case TransactionType.Check:
                            await (writer.WriteLineAsync(MemorizedTransactionListTransactionTypes.Check)).ConfigureAwait(true);
                            break;
                        case TransactionType.Deposit:
                            await (writer.WriteLineAsync(MemorizedTransactionListTransactionTypes.Deposit)).ConfigureAwait(true);
                            break;
                        case TransactionType.ElectronicPayee:
                            await (writer.WriteLineAsync(MemorizedTransactionListTransactionTypes.ElectronicPayee)).ConfigureAwait(true);
                            break;
                        case TransactionType.Investment:
                            await (writer.WriteLineAsync(MemorizedTransactionListTransactionTypes.Investment)).ConfigureAwait(true);
                            break;
                        case TransactionType.Payment:
                            await (writer.WriteLineAsync(MemorizedTransactionListTransactionTypes.Payment)).ConfigureAwait(true);
                            break;
                    }
                }
            }
        }
    }
}